classifier/admin/routes.py
from flask import flash, render_template, request, Blueprint, redirect, url_for, current_app
from sqlalchemy import desc, asc,  and_
from flask_login import current_user,logout_user, login_user, login_required
from classifier.models import User, Image, Bird
from classifier.admin.forms import ClassifyForm
from classifier import app, db, bcrypt
import classifier.image_utils as iu
import flickrapi


admin = Blueprint("admin", __name__)

@admin.route("/classify/<int:id>", methods=['GET', 'POST'])
@login_required
def classify(id):
    if request.args.get('count'):
        count = int(request.args.get('count'))
    else:
        count = 0
    arg_dic = {
        "user": User.query.filter(User.id == id).first(),
        "id": id}
    if request.method == "GET":
        birds_downloaded = Bird.query.filter(Bird.downloaded).all()
        birds_ready_to_classify = []
        for b in birds_downloaded:
            num_images_per_bird = len(Image.query.filter(Image.species==b.Name).all())
            num_images_classified = len(db.session.query(Image).filter(and_(Image.species==b.Name, Image.is_classified)).all())
            if num_images_per_bird > num_images_classified:
                birds_ready_to_classify.append(b.Name)

        arg_dic["ready_to_classify"] = birds_ready_to_classify
        return render_template("classify.html", data=arg_dic)
    if request.method == "POST":
        birdname = request.form['PickBird']

        return redirect(url_for("admin.classifying", id=id, birdname=birdname, first_flag=True,
                                reject_flag=False, count=count))


@admin.route("/classifying/<int:id>", methods=['GET', 'POST'])
@login_required
def classifying(id):
    form = ClassifyForm()
    delete_fields = "False"
    count = 0
    birdname = request.args.get('birdname')
    imagez='fred'

    if request.method == "GET":
        if (request.args.get('count')):
            count = int(request.args.get('count'))
        if request.args.get('reject_flag') == "True":
            temp_id = int(request.args.get("image_id"))
            db.session.query(Image).filter(Image.id == temp_id).delete()
            db.session.commit()
            delete_fields = "True"
        if request.args.get("unsure_flag") == 'True':
            temp_id = int(request.args.get("image_id"))
            imagez = db.session.query(Image).filter(Image.id == temp_id).first()
            newnum = imagez.num_classifications + 1
            imagez.num_classifications = newnum
            db.session.commit()
            delete_fields = "True"

    if form.validate_on_submit():
        birdname = form.birdname.data
        count = form.count.data
        temp_id = form.image_id.data
        image_folder = form.image_folder.data
        ###########        make changes to Image
        image = db.session.query(Image).filter(Image.id == int(temp_id)).first()
        if (form.is_male.data == "0") or (form.is_male.data == "1"):
            image.is_male = int(form.is_male.data)
        if (form.is_juvenile.data == "0") or (form.is_juvenile.data == "1"):
            image.is_juvenile = int(form.is_juvenile.data)
        image.is_standard = bool(form.is_standard.data)
        image.quality_of_image = int(form.quality.data)
        image.certainty = int(form.certainty.data)
        image.is_classified = True
        db.session.commit()
        count += 1
        # get commited image
        image = db.session.query(Image).filter(Image.id == temp_id).first()
        # make insertion into classifcation table
        user = User.query.filter(User.id == id).first()
        user.images.append(image)
        db.session.add(user)
        db.session.commit()
        delete_fields = "True"
    else:
        flash('Please fill in all the fields- they are all required!','danger')

  # get new image
    image_to_classify = db.session.query(Image).filter(
        and_(Image.species == birdname, Image.is_classified == False)).order_by(asc("num_classifications")).first()
    if not image_to_classify:
        flash("You classified all the images. Pick another species", "danger")
        return redirect(url_for("admin.classify", id=id, count=count))
    data = {
        "birdname": birdname,
        "id": id,
        "image_uri": image_to_classify.uri,
        "image_id": image_to_classify.id,
        "image_folder": image_to_classify.downloaded_name,
        "count": count,
    }
    return render_template("classifying.html", id=id, image=imagez, data=data, form=form, delete_fields=delete_fields)





@admin.route("/admin/downloaded", methods=['POST', 'GET'])
@login_required
def downloaded():
    """
    turn on google if you want
    :return:
    """
    to_download = request.form.getlist("species")
    # api_key = "AIzaSyD_f54RnSGEfmAxl65FkFnNOVLx36QxBOw"
    # se_id = "006513363166106579724:xubk4naonbm"
    # for each in to_download:
    #     iu.scrape(each, api_key, se_id, 20)
##############################################################
    api_key = 'b63a6d85d9aab8c4b197b76dcbd76baa'
    secret = '3c02d12d74e9d90e'
    ext_list = ['.jpg', '.png']
    per_page = 20
    number_pages = 20
    flickr = flickrapi.FlickrAPI(api_key, secret, format='parsed-json')
    for each in to_download:
        z = iu.scrap_flickr_for_photos(flickr,each,api_key,secret,per_page,number_pages,ext_list)
        print(z[0])
        print(z[1])
        print()
    flash("your images were downloaded!", "danger")
    return render_template("downloaded.html", to_download=to_download)



@admin.route("/admin", methods=["GET", "POST"])
@login_required
def admin_page():
    if current_user.id != 1:
        return redirect(url_for("main.index"))
    method = None
    # all the birds for side bar list
    birds = Bird.query.order_by("Name").all()
    # bird species that have been downloaded
    downloaded_birds = Bird.query.filter(Bird.downloaded == 1).all()
    # list of dicts- name and totals---(total downloaded, number classified
    totals = []
    # images of species, their count and the number classified
    for bird in downloaded_birds:  # each is a bird
        bird_images = Image.query.filter(Image.species == bird.Name).all()
        # number images downloaded of each species
        num_down = len(bird_images)
        # number
        classified =len([each for each in bird_images if each.is_classified])
        temp_dict = {'name': bird.Name,
                     "number_downloaded": num_down,
                     "number_classified": classified}
        totals.append(temp_dict)
    # total number of downloaded birds
    num_birds = len(downloaded_birds)
    arg_dic = {"birds": birds,
               "title": "Admin",
               "method": method,
               "num_birds": num_birds,
               "downloaded_birds": downloaded_birds,
               "stats": totals}
    if request.method == 'GET':
        multi_select = request.args.getlist("PickBirds")
        arg_dic['ms'] = multi_select

        for each in multi_select:
            if each in downloaded_birds:
                flash("{} has already been downloaded, pick birds again".format(each.Name))
                return render_template('admin.html', data=arg_dic)

        return render_template("admin.html", data=arg_dic)

    elif request.method == "POST":
        to_download = request.form.getlist("PickBirds")
        method="POST"
        arg_dic['ms'] = to_download

        return render_template('admin.html', data=arg_dic)

classifier/main/routes.py
from flask import render_template, Blueprint
import requests

main = Blueprint("main", __name__)


@main.route("/")
def index():
    return render_template('main/home.html', title="Home")


@main.route("/getting_started")
def start():
    return render_template("main/getting_started.html")

@main.route('/weather')
def weather():
    api_key = "b60a8f05df9bcdb1d7f9218c6029beaa"
    city = "Denver"
    url = "http://apiu.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid={}".format(city,api_key)

    r = requests.get(url).json()

    cities=[]
    data = {
        "city":r["name"],
        "temp":r['main']['temp'],
        "description":r['weather'][0]['description'],
        "icon":r['weather'][0]['icon']
    }
    cities.append(data)
    return render_template('main/weather.html', weather_data=cities)

classifier/users/routes.py
from flask import flash, render_template, request, Blueprint, redirect, url_for, current_app
from sqlalchemy import func, and_
from flask_login import current_user,logout_user, login_user, login_required
from classifier.models import User
from classifier.users.forms import RegistrationForm, RegistrationFormEdit, LogInForm
from classifier import db, bcrypt

users = Blueprint("users", __name__)

@users.route("/user/new", methods=['GET', 'POST'])
def create_new():
    if current_user.is_authenticated:
        flash("you are already registered", 'secondary')
        return redirect(url_for("main.index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        temp= 'password'
        user=User(email=form.email.data, qualifications=form.qualifications.data,
                  expertise=form.expertise.data, password=temp)
        db.session.add(user)
        db.session.commit()
        flash("your registration was successful. you may now log in.", 'secondary')
        return redirect(url_for("users.login_page"))
    return render_template("new.html", form=form)



@users.route("/user/<int:id>")
@login_required
def user_page(id):
    user = User.query.filter(User.id==id).first()
    num = len(user.images)
    arg_dict={
        "number_classified":num,
        "user":user,
        "id":id,
        "title":"User Page" }
    return render_template("user_page.html", data=arg_dict)


@users.route("/logout")
def logout():
    logout_user()
    flash("logged out successfully")
    return redirect(url_for("main.index"))


@users.route("/login", methods=['GET',"POST"])
def login_page():
    form = LogInForm()
    if current_user.is_authenticated:
        flash("You are already logged in", "info")
        return redirect(url_for("users.user_page",id=current_user.id))

    if form.validate_on_submit():
        user = db.session.query(User).filter_by(email=form.email.data).first()
        print('--------------------------------------------------------')
        print("user pass = {}".format(user.password))
        print(f"is true--------->{bcrypt.check_password_hash(user.password,form.password.data)}")
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user)
            flash('login successful',"success")
            return redirect(url_for('users.user_page', id=user.id))
        else:
            flash("unsuccessful login! Please try again.", "danger")
        return render_template("login.html", form=form)
    arg_dict = {
        "title":"Log In",
        "legend":"ready to review birds?",
        "msg":"Please try again"}
    return render_template("login.html", form=form, data=arg_dict)


@users.route("/user/<int:id>/edit", methods=['POST', 'GET'])
@login_required
def edit_user(id):
    form = RegistrationFormEdit()
    user = User.query.filter(User.id == id).first()
    if form.validate_on_submit():
        current_user.email = form.email.data
        current_user.expertise = form.expertise.data
        current_user.qualifications = form.qualifications.data
        if form.password.data.strip() == "":
            current_user.password = bcrypt.generate_password_hash("password")
        else:
            current_user.password = form.password.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.user_page', id=current_user.id))
    elif request.method == "GET":
        flash("change your user profile","info")
        form.email = current_user.email
        form.qualifications = current_user.qualifications
        default_ex = current_user.expertise
        #form.expertise = current_user.expertise
        form.expertise.default = default_ex
        #form.password = current_user.password
        form.process()
    data = {
        "title":"update your profile",
        "user":user}
    return render_template("user_edit.html", form=form, data=data)

classifier/templates/admin.html
{% extends "base-template.html" %}

{% block main_content %}
<div class="container-flex">
  <div class="row">
    <div class="col-md-3">
      <form action="" id="get-form" method="POST">
        <div class="mb-2">
          <select class="select-multi article-lg-font" id="PickBirds" multiple name="PickBirds">
            {% for bird in data['birds'] %}
            <option class="" value="{{ bird.Name }}">{{ bird.Name }}</option>
            {% endfor %}
          </select>
        </div>
        <!--
        this if statement is strange... fixit?
        option1= just remove it. I cant think of what would break. maybe later.
        -->
        {% if data['ms'] %}
        <input class="btn btn-sm btn-outline-dark mb-2" type="submit" value="Pick Birds to download">
        {% else %}
        <input class="btn btn-sm btn-outline-dark mb-2" type="submit" value="Pick Birds to download">
        {% endif %}
      </form>
    </div>
    <div class="col-md-6">
      {% if data['ms'] %}
      <div class="text-center" style="background-color:#b3b3b3">
        <h6>you have chosen to download photos for the following birds</h6>
        <h6>Is that correct?</h6>
      </div>
      <div class="mb-2">
        <form action="admin/downloaded" class="f" id="post-form" method="POST">
          {% for each in data['ms'] %}
          <div class="form-group">
            <input class="form-control-sm" name="species" size="35" type="text" value="{{ each }}">
          </div>
          {% endfor %}
        
        </form>
        <button class="btn btn-success mr-2" form="post-form" type="submit">Yes, begin downloads</button>
        <a href="{{ url_for('admin.admin_page') }}">
          <button class="btn btn-secondary" type="button">No, reselect bird species</button>
        </a>
      
      </div>
      <hr>
      <hr>
      {% endif %}
      <div class="mt-4">
        <h4>Downloaded Image Data</h4>
        <hr>
      </div>
      <table class="table table-bordered">
        <tr>
          <th>Species downloaded</th>
          <th>Number downloaded</th>
          <th>Number classified</th>
        
        </tr>
        {% if data['num_birds'] == 0 %}
        <tr>
          <td style="text-align:center">NONE</td>
        </tr>
        {% endif %}
        
        
        
        {#todo: is this right#}
        
        
        
        {% for stat_dict in data['stats'] %}
        <tr class="sm-table-row">
          <td style="text-align:center">{{ stat_dict['name'] }}</td>
          <td style="text-align:center">{{ stat_dict['number_downloaded'] }}</td>
          <td style="text-align:center">{{ stat_dict['number_classified'] }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
    
    <div class="col-md-3">
      <div style="height:600px;overflow:auto;">
        <table>
          <tr>
            <th>Species List</th>
          </tr>
          {% for bird in data['birds'] %}
          <tr class="sm-table-row">
            {% if bird.downloaded %}
            <td style="color:red">{{ bird.Name }}</td>
            {% else %}
            <td style="color:black">{{ bird.Name }}</td>
            {% endif %}
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>


{% endblock %}

classifier/templates/base-template.html
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
  
  
  
  <!-- js -->
  <script crossorigin="anonymous"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  
  <script crossorigin="anonymous"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  
  <script crossorigin="anonymous"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  
  
  <!-- Bootstrap CSS -->
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
  
  <link href="{{ url_for('static', filename='main2.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='site-images/favicon.ico') }}" rel="shortcut icon">
  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>Bird View</title>
  {% endif %}

</head>
<body class="container-fluid">
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">
        <img alt="Flower" class="rounded"
             src="{{ url_for('static', filename='site-images/raven_tn.jpg')}}" title="White Flower">
      </a>
      {% if legend %}
      <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">Bird's Eye</a>
      <span class="article-title muted">- {{ legend }}</span>
      {% else %}
      <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">Bird's Eye</a>
      {% endif %}
      <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation"
              class="navbar-toggler"
              data-target="#navbarToggle" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        
        <!-- Navbar Right Side -->
        
        
        {% if current_user.is_authenticated and current_user.id == 1 %}
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{{ url_for('users.user_page', id=current_user.id) }}">Your Account</a>
          <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
          <a class="nav-item nav-link" href="{{ url_for('admin.admin_page') }}">Admin</a>
        </div>
        {% elif current_user.is_authenticated %}
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{{ url_for('users.user_page', id=current_user.id) }}">Your Account</a>
          <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
        </div>
        {% else %}
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{{ url_for('main.start') }}">Getting Started</a>
          <a class="nav-item nav-link" href="{{ url_for('users.create_new') }}">Register</a>
          <a class="nav-item nav-link" href="{{ url_for('users.login_page') }}">Login</a>
        </div>
        {% endif %}
      </div>
    </div>
  
  </nav>
</header>

<main class="container-fluid">
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }}">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  
  
  {% block main_content %}
  
  {% endblock %}

</main>


<footer>
  {% block footer %}
  {% endblock %}
</footer>


<script>
function deselect(){
var elements = document.getElementsByTagName("input");
for (var inp of elements) {
    if (inp.type === "radio")
        inp.checked = false;
}
}


</script>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!--<script crossorigin="anonymous"-->
<!--        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"-->
<!--        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>-->


</body>
</html>

classifier/templates/classify.html
{% extends "base-template.html" %}

{% block main_content %}



<div class="container-flex">
  <div class="row">
    <div class="col-md-10">
      <div class="text-center">
        <h3> Bird species available to classify</h3>
        <div>Please choose a bird to classify that you are
          familiar with from the dropdown below, press "Begin" and follow
          directions on the
          following page.</div>
        <hr class="mb-4">
        <form action="#" id='pick-form' method="POST">
          <div style="background-color:#bd9e97" class="mb-4">
            <select class="select-multi2 m-2" id="PickBird" name="PickBird">
              {% for birdname in data['ready_to_classify'] %}
              <option style="font-size:20px" value="{{ birdname }}">{{ birdname }}</option>
              {% endfor %}
            </select>
          </div>
        <button style="background-color:#bd9e97" class="btn btn-lg mr-2 mt-4" form="pick-form" type="submit">Begin</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

classifier/templates/classifying.html
{% extends "base-template.html" %}

{% block main_content %}

{% from "macros.html" import radio_field %}

<div class="pl-2" style="background-color:#bd9e97; font-size:10px">
  session count = <span style="color:red">{{data['count']}}</span>
</div>
<div id="wrapper">
  <div class="row">
    <div class="booger col-md-6" style="background-color:#bd9e97;">
      <div class="alert alert-success m-1 p-0">
        <strong class="ml-2 mb-0">Directions</strong>
        <hr>
        <ul class="mb-0 article-lg-font">
          <li>
            first- reject if this is indistinguishable or useless
          </li>
          <li>
            second- skip if you are unsure of the bird's identity
          </li>
          <li>
            third- fill out the form on the right and "Classify"
          </li>
        </ul>
      </div>
      <div>
        <h4 class="mt-2">{{ data['birdname'] }}?
          <span class="pl-4">
          <a class="reject-button text-center" href="{{ url_for('admin.classifying', id=data['id'], reject_flag=True,
          image_id=data['image_id'], count=data['count'], birdname=data['birdname']) }}">REJECT</a>
          </span>
          <span class="pl-4">
            <a class="skip-button text-center" href="{{ url_for('admin.classifying', id=data['id'],
            reject_flag=False, unsure_flag=True, image_id=data['image_id'], count=data['count'], birdname=data['birdname']) }}">SKIP</a>
          </span>
        </h4>
      </div>
      <img
          class="mt-2 mb-2"
          src="{{ url_for('static', filename='images/downloaded/' + data['image_folder'] + '/'
          + data['image_uri'] ) }}"
          style="width:100%">
    </div>
    <div class="col-md-6 pl-4 pt-2">
      <div class="text-center">
        <h5>Bird ID Form</h5>
      </div>
      <form action="#" class="" id="class-form" method="POST">
        {{ form.hidden_tag() }}
        <div>
          {{ radio_field(form.is_male) }}
          {{ radio_field(form.is_juvenile) }}
          {{ radio_field(form.is_standard) }}
          {{ radio_field(form.quality) }}
          {{ radio_field(form.certainty) }}
        </div>
        <input name="image_id" type="hidden" value="{{ data['image_id'] }}">
        <input name="image_folder" type="hidden" value="{{ data['image_folder'] }}">
        <input id="count" name="count" type="hidden" value="{{ data['count'] }}">
        <input name="birdname" type="hidden" value="{{ data['birdname'] }}">
        <div>
          <div class="text-center mt-4">
            <input class="btn btn-danger class-button" type="submit" value="Classify">
          </div>
          <div class="text-center pt-4">
            <button class="btn btn-danger class-button2" onclick="deselect()" type="button">Clear inputs</button>
          </div>
        </div>
      </form>
      <div>
        <h1>{{ imagez }}</h1>
      </div>
      
      {% if delete_fields == "True" %}
      <script>
    var elements = document.getElementsByTagName("input");
      for (var inp of elements) {
        if (inp.type === "radio")
          inp.checked = false;}
      
      
      
      </script>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

classifier/templates/downloaded.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<h1>downloaded</h1>
<h1>{{ to_download }}</h1>

<a href="{{ url_for('admin.admin_page') }}" >Back to Admin Page</a>
</body>
</html>

classifier/templates/macros.html
{% macro render_field(field) %}
<dt>{{ field.label(class="form-control-label") }}</dt>
<dd >{{ field(class="form-control, form-control-lg", **kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_registration(field) %}
  <dt>{{ field.label(class="form-control-label") }}
  <dd>{{ field(class="form-control, form-control-lg", **kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}


{% macro nav_bar() %}
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">
        <img alt="Flower" class="rounded"
             src="{{ url_for('static', filename='site-images/raven_tn.jpg')}}" title="White Flower">
      </a>
      {% if legend %}
      <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">Bird's Eye</a>
      <span class="article-title muted">- {{ legend }}</span>
      {% else %}
      <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">Bird's Eye</a>
      {% endif %}
      <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation"
              class="navbar-toggler"
              data-target="#navbarToggle" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        
        <!-- Navbar Right Side -->
        {% if current_user.is_authenticated %}
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Account</a>
          <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
        </div>
        {% else %}
   
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{{ url_for('main.start') }}">Getting Started</a>
          <a class="nav-item nav-link" href="{{ url_for('users.create_new') }}">Register</a>
          <a class="nav-item nav-link" href="{{ url_for('users.login_page') }}">Login</a>
        </div>
        {% endif %}
      </div>
    </div>
  
  </nav>
</header>
{% endmacro %}

{% macro radio_field(field) %}
        <div class="border">
          <div class=row>
            <div class="col-form-label col-sm-4 "><span class="pl-1">{{ field.label }}</span></div>
            <div class="col-sm-8">
              <div class="form-check">
                {% for subfield in field %}
                  <div class="field">{{ subfield }} <span class="class_label">{{ subfield.label }}</span></div>
                {% endfor %}
              </div>
              {% if field.errors %}
              <ul>
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
          </div>
        </div>
{% endmacro %}

{% macro select_field(field) %}
        <div class="border">
          <div class=row>
            <div class="col-form-label col-sm-4 "><span class="pl-1">{{ field.label }}</span></div>
            <div class="col-sm-8">
              <div class="form-check">
                {% for subfield in field %}
                <input>
                  <div class="field">{{ subfield }} <span class="class_label">{{ subfield.label }}</span></div>
                
                {% endfor %}
              </div>
              {% if field.errors %}
              <ul>
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
          </div>
        </div>
{% endmacro %}


{% macro render_field(field) %}
<dt>{{ field.label(class="form-control-label") }}</dt>
<dd >{{ field(class="form-control, form-control-lg", **kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}